[project]
pudl_release = "v2025.7.0"
# colo generates colo data, otherwise CR
balancing_authorities = []
regime = "limited"
solar_ilr = 1.34

[data]
max_solar_distance = 10.0
max_wind_distance = 45.0
extend_cems = true
re_by_plant = true
min_re_site_mw = 25.0


[colo.data]
technology_description = { comp = "in", alt_name = "icx_tech", item = [
    "Natural Gas Steam Turbine",
    "Conventional Steam Coal",
    "Natural Gas Fired Combined Cycle",
    "Natural Gas Fired Combustion Turbine",
    "Petroleum Liquids",
    "Natural Gas Internal Combustion Engine",
    "Wood/Wood Waste Biomass",
    "Coal Integrated Gasification Combined Cycle",
    "Other Gases",
    "Petroleum Coke",
    "Landfill Gas",
    "Natural Gas with Compressed Air Storage",
    "All Other",
    "Other Waste Biomass",
    "Other Natural Gas",
] }
ever_gas = { comp = "is_true" }
capacity_mw = { comp = "ge", alt_name = "icx_capacity", item = 150.0 }
min_retirement_year = 2028
min_operating_year = 1995
reg_rank = [ 1, 2, 3, 4, 5, 6, 7, 8, 9 ]

[colo.project]
scenarios = [
    "clean",
    "dirty",
    "pure_surplus",
    "form",
    "form_fos",
    "clean_xhc",
    "dirty_xhc",
    "pure_surplus_xhc",
    "form_xhc",
    "form_fos_xhc",
]
# relative to home or user dir
#data_path = "patio_data/colo_data"
#colo_json_path = "patio_data/colo_data/colo.json"
data_path = "patio_data/colo_data_20250706"
colo_json_path = "patio_data/colo_data_20250706/colo.json"
run_dir_path = "patio_data/colo_{NOW}"
workers = 8
plant_ids = []

[colo.scenario.default]
ix = -1
techs = []
setting.run_econ = true
param.num_crit_hrs = 25
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 1.0
param.mkt_rev_mult = 0.5
param.fos_load_cost_mult = 3.0
param.gas_window_max_hrs = 12
param.gas_window_max_mult = 1.25  # we want to see violations for seasonal
param.stored_fuel_hrs = 48
# https://www.rila.org/retail-compliance-center/emergency-generator-permitting-matrix
param.backup_max_hrs_per_year = 250
param.solar_degrade_per_year = 0.0
param.life = 30
param.build_year = 2026
param.atb_scenario = "Moderate"
param.aeo_report_year = 2023
param.aeo_scenario = "reference"
param.ptc = 0.0
param.itc = 0.3
param.gas_window_seasonal = false
param.con_fossil_load_hrly = false
param.opt_years = [ 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039 ]
dv.FlexLoad = { uptime = 0.0, ld_value_select = 1000, ld_value = 10000, min_load = 0.5, sqkm_per_mw = 0.004 }
dv.Renewables = {}
dv.EndogenousDurationStorage = { pre_charge = 0.5, min_soc_hrs = 1 }
dv.CleanExport = {}
dv.Curtailment = {}

[colo.scenario.clean]
ix = 1002
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_fos = 0.05
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[colo.scenario.dirty]
ix = 1008
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_fos = 0.4
param.max_pct_hist_fos = 20.0
param.load_icx_max_mult = 0.75
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[colo.scenario.pure_surplus]
ix = 1010
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 10.0
dv.ExportIncumbentFossil = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "natural_gas" }

[colo.scenario.form]
ix = 1011
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
dv.ExportIncumbentFossil = {}
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }

[colo.scenario.form_fos]
ix = 1013
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 10.0
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }
dv.ExportIncumbentFossil = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "natural_gas" }

[colo.scenario.clean_xhc]
ix = 1102
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_fos = 0.05
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
param.mkt_rev_mult = 1.0
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[colo.scenario.dirty_xhc]
ix = 1108
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_fos = 0.4
param.max_pct_hist_fos = 20.0
param.load_icx_max_mult = 0.75
param.mkt_rev_mult = 1.0
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[colo.scenario.pure_surplus_xhc]
ix = 1110
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 10.0
param.mkt_rev_mult = 1.0
dv.ExportIncumbentFossil = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "natural_gas" }

[colo.scenario.form_xhc]
ix = 1111
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
param.mkt_rev_mult = 1.0
dv.ExportIncumbentFossil = {}
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }

[colo.scenario.form_fos_xhc]
ix = 1113
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 10.0
param.mkt_rev_mult = 1.0
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }
dv.ExportIncumbentFossil = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "natural_gas" }

[colo.scenario.rei_pure_surplus]
ix = 1210
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 100.0
techs = [ "Solar Photovoltaic", "Onshore Wind Turbine" ]
dv.ExportIncumbentFixed = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "ethanol" }

[colo.scenario.rei_form]
ix = 1211
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 100.0
techs = [ "Solar Photovoltaic", "Onshore Wind Turbine" ]
dv.ExportIncumbentFixed = {}
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }

[colo.scenario.rei_form_fos]
ix = 1213
param.num_crit_hrs = 0
param.max_pct_fos = 0.2
param.max_pct_hist_fos = 3.0
param.load_icx_max_mult = 100.0
dv.FeStorage = { pre_charge = 0.5, min_soc_hrs = 1 }
techs = [ "Solar Photovoltaic", "Onshore Wind Turbine" ]
dv.ExportIncumbentFixed = {}
dv.LoadNewFossil = { tech = "rice", primary_fuel = "ethanol" }

[colo.scenario.thermal_load]
ix = 22
param.num_crit_hrs = 25
param.max_pct_fos = 0.05
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
dv.IncumbentFossil = {}
dv.Curtailment = { min_cost = 0.05 }
dv.ThermalStorageLoad = {}

[colo.scenario.moderate]
ix = 1000
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_hist_fos = 20.0
param.load_icx_max_mult = 0.75
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[colo.scenario.moderate_ej]
ix = 1001
techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
param.max_pct_hist_fos = 1.0
param.load_icx_max_mult = 0.75
dv.ExportIncumbentFossil = {}
dv.LoadIncumbentFossil = {}

[cr.project]
# 'both', true, false
re_limits_dispatch = true
include_figs = false
cr_eligible_techs = [ "Natural Gas Fired Combined Cycle", "Natural Gas Fired Combustion Turbine" ]
scenarios = [
    { re_energy = 0.2, storage_li_pct = 0.0 },
    { re_energy = 0.2, storage_li_pct = 0.25 },
    { re_energy = 0.4, storage_li_pct = 0.0 },
    { re_energy = 0.4, storage_li_pct = 0.25 },
    { re_energy = 0.6, storage_li_pct = 0.0 },
    { re_energy = 0.6, storage_li_pct = 0.25 },
    { re_energy = 0.8, storage_li_pct = 0.0 },
    { re_energy = 0.8, storage_li_pct = 0.25 },
]
